<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:tns="http://www.example.org/FireEmployee/" targetNamespace="http://www.example.org/FireEmployee/Artifacts" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <partnerLinkType name="FireEmployeePLT" xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <role name="FireEmployeeRole" portType="tns:FireEmployee"/>
  </partnerLinkType>
  <import location="FireEmployee.wsdl" namespace="http://www.example.org/FireEmployee/"/>
</definitions>
