<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:tns="http://www.example.org/isEmployeeWorkingAtThisBusiness/"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:pref="http://www.example.org/DniAndBusiness/"
    xmlns:pref1="http://www.example.org/Bool/"
    name="isEmployeeWorkingAtThisBusiness"
     targetNamespace="http://www.example.org/isEmployeeWorkingAtThisBusiness/">
     
     
   <wsdl:types>
       <xsd:schema
    	targetNamespace="http://www.example.org/isEmployeeWorkingAtThisBusiness/">
    	
    	<xsd:import	schemaLocation="relocated/DniIdAndBusinessId.xsd"
    				namespace="http://www.example.org/DniAndBusiness/">
    	</xsd:import>
    	<xsd:import schemaLocation="relocated/Bool.xsd"
    				namespace="http://www.example.org/Bool/"></xsd:import>
        </xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="isEmployeeWorkingAtThisBusinessRequest">
		<wsdl:part element="pref:DniIdAndBusinessId" name="DniIdAndBusinessId" />
  </wsdl:message>
	
	<wsdl:message name="isEmployeeWorkingAtThisBusinessResponse">
		<wsdl:part element="pref1:Bool"	name="IsWorking" />
	</wsdl:message>
  
  
  <wsdl:portType name="isEmployeeWorkingAtThisBusiness">
    <wsdl:operation name="isEmployeeWorkingAtThisBusiness">
      <wsdl:input message="tns:isEmployeeWorkingAtThisBusinessRequest"/>
      <wsdl:output message="tns:isEmployeeWorkingAtThisBusinessResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="isEmployeeWorkingAtThisBusinessSOAP" type="tns:isEmployeeWorkingAtThisBusiness">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="isEmployeeWorkingAtThisBusiness">
      <soap:operation soapAction="http://www.example.org/isEmployeeWorkingAtThisBusiness/isEmployeeWorkingAtThisBusiness"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="isEmployeeWorkingAtThisBusiness">
    <wsdl:port binding="tns:isEmployeeWorkingAtThisBusinessSOAP" name="isEmployeeWorkingAtThisBusinessSOAP">
      <soap:address location="http://www.odehost.com:8080/ode/processes/isEmployeeWorkingAtThisBusiness"/>
    </wsdl:port>
  </wsdl:service>  
</wsdl:definitions>
