package proyectomtis.ws.soap.fireemployee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-05-18T23:29:23.506+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "FireEmployee", 
                  wsdlLocation = "http://www.odehost.com:8080/ode/processes/FireEmployee?wsdl",
                  targetNamespace = "http://www.example.org/FireEmployee/") 
public class FireEmployee extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/FireEmployee/", "FireEmployee");
    public final static QName FireEmployeeSOAP = new QName("http://www.example.org/FireEmployee/", "FireEmployeeSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://www.odehost.com:8080/ode/processes/FireEmployee?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FireEmployee.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.odehost.com:8080/ode/processes/FireEmployee?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FireEmployee(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FireEmployee(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FireEmployee() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FireEmployee(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FireEmployee(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FireEmployee(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FireEmployeePortType
     */
    @WebEndpoint(name = "FireEmployeeSOAP")
    public FireEmployeePortType getFireEmployeeSOAP() {
        return super.getPort(FireEmployeeSOAP, FireEmployeePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FireEmployeePortType
     */
    @WebEndpoint(name = "FireEmployeeSOAP")
    public FireEmployeePortType getFireEmployeeSOAP(WebServiceFeature... features) {
        return super.getPort(FireEmployeeSOAP, FireEmployeePortType.class, features);
    }

}
