
package proyectomtis.ws.soap.fireemployee;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-05-18T23:29:23.454+02:00
 * Generated source version: 2.5.1
 * 
 */
public final class FireEmployeePortType_FireEmployeeSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/FireEmployee/", "FireEmployee");

    private FireEmployeePortType_FireEmployeeSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FireEmployee.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FireEmployee ss = new FireEmployee(wsdlURL, SERVICE_NAME);
        FireEmployeePortType port = ss.getFireEmployeeSOAP();  
        
        {
        System.out.println("Invoking fireEmployee...");
        proyectomtis.ws.soap.fireemployee.DniIdAndBusinessId _fireEmployee_dniIdAndBusinessId = null;
        proyectomtis.ws.soap.fireemployee.IsOkAndFireEmployeeReport _fireEmployee__return = port.fireEmployee(_fireEmployee_dniIdAndBusinessId);
        System.out.println("fireEmployee.result=" + _fireEmployee__return);


        }

        System.exit(0);
    }

}
