package mtis.ws.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-05-26T21:55:05.523+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "isEmployeeWorkingAtThisBusiness", 
                  wsdlLocation = "file:/file:/C:/Users/Panfri/MTIS Enrique/isemployeeworkingatthisbusiness/isEmployeeWorkingAtThisBusiness.wsdl",
                  targetNamespace = "http://www.example.org/isEmployeeWorkingAtThisBusiness/") 
public class IsEmployeeWorkingAtThisBusiness_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/isEmployeeWorkingAtThisBusiness/", "isEmployeeWorkingAtThisBusiness");
    public final static QName IsEmployeeWorkingAtThisBusinessSOAP = new QName("http://www.example.org/isEmployeeWorkingAtThisBusiness/", "isEmployeeWorkingAtThisBusinessSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/file:/C:/Users/Panfri/MTIS Enrique/isemployeeworkingatthisbusiness/isEmployeeWorkingAtThisBusiness.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IsEmployeeWorkingAtThisBusiness_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/file:/C:/Users/Panfri/MTIS Enrique/isemployeeworkingatthisbusiness/isEmployeeWorkingAtThisBusiness.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IsEmployeeWorkingAtThisBusiness_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IsEmployeeWorkingAtThisBusiness_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IsEmployeeWorkingAtThisBusiness_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IsEmployeeWorkingAtThisBusiness_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IsEmployeeWorkingAtThisBusiness_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IsEmployeeWorkingAtThisBusiness_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IsEmployeeWorkingAtThisBusiness
     */
    @WebEndpoint(name = "isEmployeeWorkingAtThisBusinessSOAP")
    public IsEmployeeWorkingAtThisBusiness getIsEmployeeWorkingAtThisBusinessSOAP() {
        return super.getPort(IsEmployeeWorkingAtThisBusinessSOAP, IsEmployeeWorkingAtThisBusiness.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IsEmployeeWorkingAtThisBusiness
     */
    @WebEndpoint(name = "isEmployeeWorkingAtThisBusinessSOAP")
    public IsEmployeeWorkingAtThisBusiness getIsEmployeeWorkingAtThisBusinessSOAP(WebServiceFeature... features) {
        return super.getPort(IsEmployeeWorkingAtThisBusinessSOAP, IsEmployeeWorkingAtThisBusiness.class, features);
    }

}
