package mtis.ws.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-05-26T21:55:05.512+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.example.org/isEmployeeWorkingAtThisBusiness/", name = "isEmployeeWorkingAtThisBusiness")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IsEmployeeWorkingAtThisBusiness {

    @WebResult(name = "BoolResponse", targetNamespace = "http://www.example.org/BoolResponse/", partName = "IsWorking")
    @WebMethod(action = "http://www.example.org/isEmployeeWorkingAtThisBusiness/isEmployeeWorkingAtThisBusiness")
    public BoolResponse isEmployeeWorkingAtThisBusiness(
        @WebParam(partName = "DniIdAndBusinessId", name = "DniIdAndBusinessId", targetNamespace = "http://www.example.org/DniAndBusiness/")
        DniIdAndBusinessId dniIdAndBusinessId
    );
}
